# Generated by Django 3.2.6 on 2023-01-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='bio',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
